### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by retallicka** [DTVD/rainbowstream#114]
Just tried starting it and got this error after entering the pin code. I'm using version 1.2.7

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/rainbowstream/rainbow.py", line 2003, in stream
    tweet_iter = stream.user(**query_args)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/Library/Python/2.7/site-packages/twitter/stream.py", line 284, in _handle_response
    _timeout or timeout, heartbeat_timeout)
  File "/Library/Python/2.7/site-packages/twitter/stream.py", line 209, in handle_stream_response
    raise TwitterHTTPError(e, uri, 'json', arg_data)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 72, in __init__
    data = json.loads(data.decode('utf8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by DTVD** [comment]
This should be fixed in latest version of Rainbowstream and Python Twitter Tool. Try to update
```bash
pip install -U rainbowstream
```
