### ISSUE TITLE
Abruptly stopped working 

### ISSUE THREAD

**Issue by Grimmoire** [DTVD/rainbowstream#115]
```
$ rainbowstream
Traceback (most recent call last):
  File "/usr/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==1.2.7', 'console_scripts', 'rainbowstream')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/rainbowstream/rainbow.py", line 16, in <module>
    from twitter.stream import TwitterStream, Timeout, HeartbeatTimeout, Hangup
  File "/usr/lib/python3.4/site-packages/twitter/__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'
```

**Comment by DTVD** [comment]
I thinks this should be fine now. Try to update to latest version of Rainbowstream and dependencies also
```
pip install -U rainbowstream
```
