### ISSUE TITLE
HELP ME! eggs thingy

### ISSUE THREAD

**Issue by firefl1es** [DTVD/rainbowstream#116]
Collecting rainbowstream
  Using cached rainbowstream-1.2.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-2b05p4jz/rainbowstream/setup.py", line 31, in <module>
        long_description=open("./README.rst", "r").read(),
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 404: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2b05p4jz/rainbowstream

OS - Arch Linux
Python version 3.4.3

**Comment by laxtiz** [comment]
use utf-8 plz.
```shell
sed -i "/ja_JP\.UTF-8/{s/^#\?//}" /etc/locale.gen
locale-gen
localectl set-locale LANG=ja_JP.utf8
```
maybe you need `sudo`.

**Comment by unixg33k** [comment]
For Arch I was able to get around this error by using python2.

pacman -S python2-pip
pip2 install rainbowstream
