### ISSUE TITLE
CYCLE_COLOR not accepting strings

### ISSUE THREAD

**Issue by wadegbow** [DTVD/rainbowstream#119]
I'm attempting to create a theme that uses my terminals base colors, but the CYCLE_COLOR array only works with integers. 

```
"CYCLE_COLOR" :["magenta","cyan","green","blue"]
```

causes the following KeyError:

```
Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==1.2.7', 'console_scripts', 'rainbowstream')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/rainbow.py", line 22, in <module>
    from .draw import *
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/draw.py", line 1116, in <module>
    start_cycle()
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/draw.py", line 40, in start_cycle
    dg['cyc'] = init_cycle()
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/draw.py", line 32, in init_cycle
    for i in c['CYCLE_COLOR']]
  File "/usr/local/lib/python3.4/site-packages/rainbowstream/draw.py", line 32, in <listcomp>
    for i in c['CYCLE_COLOR']]
KeyError: b'magenta'
```
I would be happy with using the color codes, but they don't seem to be the same colors. Using `35` doesn't produce the same color as `"magenta"`.

**Comment by DTVD** [comment]
Seems this is a bug while RS running on Python3. Will take a look in details. Thanks!
