### ISSUE TITLE
not working with python-requests 2.7.0...

### ISSUE THREAD

**Issue by murrayf** [DTVD/rainbowstream#126]
Hi,

I'm pretty excited to use new rs-1.3.1 but I have an issue in my fedora23alpha with python request library (I'm using python-2.7)...

When I run rainbowstream, I got this python error:
Traceback (most recent call last):
  File "/usr/bin/rainbowstream", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.5.3' distribution was not found and is required by rainbowstream

... To make program works is necessary to install manually requests 2.5.3, but this library is upgraded with python-pip to version 2.7.0, and rs is not working...

Thanks a lot,

Alberto. :)

**Comment by Tenzer** [comment]
How did you install Rainbowstream? I would assume requests got installed in the right version along with Rainbowstream. It looks like you have installed it globally on your machine, perhaps there's another version of requests installed on the system which takes precedence over the version Rainbowstream wants?

**Comment by murrayf** [comment]
Hi Jeppe,

Yes, fedora23a comes with python-3.4 preinstalled. I have uninstalled 
rs and reinstalled through pip3 and everything seems to work again.

Thanks a lot,

Alberto.

:)
