### ISSUE TITLE
installation in the quick way doesn't work: Exception!

### ISSUE THREAD

**Issue by marianoju** [DTVD/rainbowstream#178]
My OS: Ubuntu 16.04
My Python version: Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 

> user@box3:~$ sudo pip install rainbowstream
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting rainbowstream
  Downloading rainbowstream-1.3.3.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 845kB/s 
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from rainbowstream)
Collecting arrow (from rainbowstream)
  Downloading arrow-0.8.0.tar.gz (81kB)
    100% |████████████████████████████████| 81kB 1.7MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by DTVD** [comment]
It seems to be a problem with pip version. You may upgrade pip version as the log said, or use the virtualenv way instead.
