### ISSUE TITLE
Installation breaks on FreeBSD 10.2

### ISSUE THREAD

**Issue by mareksagan** [DTVD/rainbowstream#180]
I have done both "ways" of installation and it breaks... Running Python 2.7.

Here is the log:

> # pip install rainbowstream
> Collecting rainbowstream
>   Using cached rainbowstream-1.3.3.tar.gz
> Collecting python-dateutil (from rainbowstream)
>   Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
> Collecting arrow (from rainbowstream)
>   Using cached arrow-0.8.0.tar.gz
> Collecting requests==2.5.3 (from rainbowstream)
>   Using cached requests-2.5.3-py2.py3-none-any.whl
> Collecting pyfiglet (from rainbowstream)
>   Using cached pyfiglet-0.7.5.tar.gz
> Collecting twitter (from rainbowstream)
>   Using cached twitter-1.17.1-py2.py3-none-any.whl
> Collecting Pillow (from rainbowstream)
>   Using cached Pillow-3.3.0.zip
> Collecting PySocks (from rainbowstream)
>   Using cached PySocks-1.5.7.tar.gz
> Collecting six>=1.5 (from python-dateutil->rainbowstream)
>   Downloading six-1.10.0-py2.py3-none-any.whl
> Building wheels for collected packages: rainbowstream, arrow, pyfiglet, Pillow, PySocks
>   Running setup.py bdist_wheel for rainbowstream ... done
>   Stored in directory: /root/.cache/pip/wheels/ce/a6/ee/78d894d77cee1169cf0db3a9a60705fc28ddf6880cae21cd28
>   Running setup.py bdist_wheel for arrow ... done
>   Stored in directory: /root/.cache/pip/wheels/02/3c/e7/9c309baa019baa80e0505e7d4a4ceb47458fd750faaad53724
>   Running setup.py bdist_wheel for pyfiglet ... done
>   Stored in directory: /root/.cache/pip/wheels/22/64/50/061d962f0938800687c7d965aec42c3c3b5344634f2242f3d8
>   Running setup.py bdist_wheel for Pillow ... error
>   Complete output from command /usr/ports/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5ol_Fx/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpzuIKzipip-wheel- --python-tag cp27:
>   Single threaded build, not installing mp_compile:1 processes
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.freebsd-10.2-RELEASE-amd64-2.7
>   creating build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageGrab.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/TiffImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/MicImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/FitsStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ExifTags.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageChops.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/CurImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageEnhance.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/WebPImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PngImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/DcxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/TgaImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PsdImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/JpegPresets.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GimpPaletteFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GbrImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/OleFileIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PSDraw.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/_binary.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageSequence.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/DdsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/McIdasImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/IptcImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageTransform.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PdfImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/JpegImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/FontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/Hdf5StubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PcxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/WalImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageQt.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/IcnsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/BufrStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/EpsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/TiffTags.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/BmpImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/MpoImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GimpGradientFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/SgiImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageCms.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageDraw2.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageStat.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/_tkinter_finder.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/SpiderImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageWin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/Jpeg2KImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/__init__.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImagePalette.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/FtexImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/Image.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/SunImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageFont.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageTk.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/TarIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageShow.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PpmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/XpmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageColor.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PyAccess.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GifImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImagePath.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageFilter.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageMode.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/features.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GdImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ContainerIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/MspImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PalmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageMath.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/FliImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/MpegImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PcfFontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/XbmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageOps.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageDraw.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PixarImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/BdfFontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/FpxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/IcoImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImtImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PcdImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/PaletteFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/_util.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/ImageMorph.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/XVThumbImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/WmfImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   copying PIL/GribStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   running egg_info
>   writing Pillow.egg-info/PKG-INFO
>   writing top-level names to Pillow.egg-info/top_level.txt
>   writing dependency_links to Pillow.egg-info/dependency_links.txt
>   warning: manifest_maker: standard file '-c' not found
> 
>   reading manifest file 'Pillow.egg-info/SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   warning: no files found matching '*.sh'
>   no previously-included directories found matching 'docs/_static'
>   warning: no previously-included files found matching '.coveragerc'
>   warning: no previously-included files found matching '.editorconfig'
>   warning: no previously-included files found matching '.landscape.yaml'
>   warning: no previously-included files found matching 'appveyor.yml'
>   warning: no previously-included files found matching 'build_children.sh'
>   warning: no previously-included files found matching 'tox.ini'
>   warning: no previously-included files matching '.git*' found anywhere in distribution
>   warning: no previously-included files matching '*.pyc' found anywhere in distribution
>   warning: no previously-included files matching '*.so' found anywhere in distribution
>   writing manifest file 'Pillow.egg-info/SOURCES.txt'
>   copying PIL/OleFileIO-README.md -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>   running build_ext
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-build-5ol_Fx/Pillow/setup.py", line 753, in <module>
>       zip_safe=not debug_build(), )
>     File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
>       dist.run_commands()
>     File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
>       self.run_command(cmd)
>     File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/usr/ports/venv/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
>       self.run_command('build')
>     File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
>       self.run_command(cmd_name)
>     File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
>       self.build_extensions()
>     File "/tmp/pip-build-5ol_Fx/Pillow/setup.py", line 521, in build_extensions
>       ' using --disable-%s, aborting' % (f, f))
>   ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
> 
>   ----------------------------------------
>   Failed building wheel for Pillow
>   Running setup.py clean for Pillow
>   Running setup.py bdist_wheel for PySocks ... done
>   Stored in directory: /root/.cache/pip/wheels/cf/81/67/77884514e566867d5223e5530e27ce9b9433b78c766a400313
> Successfully built rainbowstream arrow pyfiglet PySocks
> Failed to build Pillow
> Installing collected packages: six, python-dateutil, arrow, requests, pyfiglet, twitter, Pillow, PySocks, rainbowstream
>   Running setup.py install for Pillow ... error
>     Complete output from command /usr/ports/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5ol_Fx/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wowVLV-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/ports/venv/include/site/python2.7/Pillow:
>     Single threaded build, not installing mp_compile:1 processes
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.freebsd-10.2-RELEASE-amd64-2.7
>     creating build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageGrab.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/TiffImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/MicImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/FitsStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ExifTags.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageChops.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/CurImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageEnhance.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/WebPImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PngImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/DcxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/TgaImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PsdImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/JpegPresets.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GimpPaletteFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GbrImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/OleFileIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PSDraw.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/_binary.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageSequence.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/DdsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/McIdasImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/IptcImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageTransform.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PdfImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/JpegImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/FontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/Hdf5StubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PcxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/WalImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageQt.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/IcnsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/BufrStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/EpsImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/TiffTags.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/BmpImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/MpoImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GimpGradientFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/SgiImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageCms.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageDraw2.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageStat.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/_tkinter_finder.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/SpiderImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageWin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/Jpeg2KImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/__init__.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImagePalette.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/FtexImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/Image.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/SunImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageFont.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageTk.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/TarIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageShow.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PpmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/XpmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageColor.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PyAccess.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GifImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImagePath.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageFilter.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageMode.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/features.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GdImageFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ContainerIO.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/MspImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PalmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageMath.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/FliImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/MpegImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PcfFontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/XbmImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageOps.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageDraw.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PixarImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/BdfFontFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/FpxImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/IcoImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImtImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PcdImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/PaletteFile.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/_util.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/ImageMorph.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/XVThumbImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/WmfImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     copying PIL/GribStubImagePlugin.py -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     running egg_info
>     writing Pillow.egg-info/PKG-INFO
>     writing top-level names to Pillow.egg-info/top_level.txt
>     writing dependency_links to Pillow.egg-info/dependency_links.txt
>     warning: manifest_maker: standard file '-c' not found
> 
>     reading manifest file 'Pillow.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     warning: no files found matching '*.sh'
>     no previously-included directories found matching 'docs/_static'
>     warning: no previously-included files found matching '.coveragerc'
>     warning: no previously-included files found matching '.editorconfig'
>     warning: no previously-included files found matching '.landscape.yaml'
>     warning: no previously-included files found matching 'appveyor.yml'
>     warning: no previously-included files found matching 'build_children.sh'
>     warning: no previously-included files found matching 'tox.ini'
>     warning: no previously-included files matching '.git*' found anywhere in distribution
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
>     warning: no previously-included files matching '*.so' found anywhere in distribution
>     writing manifest file 'Pillow.egg-info/SOURCES.txt'
>     copying PIL/OleFileIO-README.md -> build/lib.freebsd-10.2-RELEASE-amd64-2.7/PIL
>     running build_ext
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-5ol_Fx/Pillow/setup.py", line 753, in <module>
>         zip_safe=not debug_build(), )
>       File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
>         dist.run_commands()
>       File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/usr/ports/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/local/lib/python2.7/distutils/command/install.py", line 563, in run
>         self.run_command('build')
>       File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
>         self.run_command(cmd_name)
>       File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/tmp/pip-build-5ol_Fx/Pillow/setup.py", line 521, in build_extensions
>         ' using --disable-%s, aborting' % (f, f))
>     ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
> 
>     ----------------------------------------
> Command "/usr/ports/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5ol_Fx/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wowVLV-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/ports/venv/include/site/python2.7/Pillow" failed with error code 1 in /tmp/pip-build-5ol_Fx/Pillow/
> 

>

**Comment by DTVD** [comment]
It seems that you need `libjpeg` and `zlib` in your system to install rainbowstream.

**Comment by koobs** [comment]
@mareksagan This is a Pillow build system issue, unrelated to rainbowstream except to the extent that it prevents completion of installation.

**Note:** I created a port for rainbowstream on the 4th of august to make installation easier:

Ports: 
 * ` $ cd /usr/ports/net/py-rainbowstream && sudo make install clean`, OR
 * **portmaster** or **portupgrade**  `net/py-rainbowstream`

Packages:
 * `# pkg install py27-rainbowstream`

**Comment by losmike** [comment]
Recently installed rainbowstream and was successful with the below packages. 

$ pkg install python py37-pip py37-pillow-7.0.0 
$ pip install rainbowstream

**Comment by koobs** [comment]
@losmike What FreeBSD version? Note also that FreeBSD 10.x is now End-of-Life. If the issue is still reproducible on supported FreeBSD versions, please let us know, otherwise this issue can be closed OBE

**Comment by losmike** [comment]
Doh, sorry for not adding that. I was testing FreeBSD 12.2.

**Comment by koobs** [comment]
> Doh, sorry for not adding that. I was testing FreeBSD 12.2.

All good, thanks! This issue can be closed OBE. It can be reopened is the issue is or becomes reproducible in a supported FreeBSD version.
