### ISSUE TITLE
'Quick way' installation not working `ImportError: cannot import name 'TwitterCall'`

### ISSUE THREAD

**Issue by therockmandolinist** [DTVD/rainbowstream#182]
OS: OSX 10.11.5
Python: Python 3.5.2

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 7, in <module>
    from rainbowstream.rainbow import fly
  File "/usr/local/lib/python3.5/site-packages/rainbowstream/rainbow.py", line 16, in <module>
    from twitter.stream import TwitterStream, Timeout, HeartbeatTimeout, Hangup
  File "/usr/local/lib/python3.5/site-packages/twitter/stream.py", line 18, in <module>
    from .api import TwitterCall, wrap_response, TwitterHTTPError
ImportError: cannot import name 'TwitterCall'
```

**Comment by therockmandolinist** [comment]
Apologies, a force reinstall of the twitter package fixed this.
