### ISSUE TITLE
ImportError: No module named 'rainbowstream.consumer'

### ISSUE THREAD

**Issue by gregf** [DTVD/rainbowstream#205]
I'm trying to get the archlinux package for rainbowstream updated over [here](https://aur.archlinux.org/packages/rainbowstream/).

It installs fine, but when I run it I get the following error.

```
Traceback (most recent call last):
  File "/usr/bin/rainbowstream", line 11, in <module>
    load_entry_point('rainbowstream==1.3.6', 'console_scripts', 'rainbowstream')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/rainbowstream/rainbow.py", line 28, in <module>
    from .consumer import *
ImportError: No module named 'rainbowstream.consumer'
```

**Comment by drselump14** [comment]
from readme

Create a file consumer.py in rainbowstream folder with following content

`# Consumer information
CONSUMER_KEY = 'APIKey' # Your Twitter application's API key
CONSUMER_SECRET = 'APISecret' # Your Twitter application's API secret
PCKT_CONSUMER_KEY = 'PocketAPIKey' # Your Pocket application's API key`

the rainbowstream folder is a child folder inside the repository

**Comment by gregf** [comment]
Duh! Sorry to waste your time.
