### ISSUE TITLE
Feature Request: put completer.hist at a centralised place

### ISSUE THREAD

**Issue by b3yond** [DTVD/rainbowstream#231]
Hi,

every time I tweet with rainbowstream, a completer.hist file is created wherever I opened the program. lots of waste which confuses my file system :P 

could we maybe store the file in a central space? I guess it would fit the whole idea of making a history better, if there weren't loads of different historys.

**Comment by Neo-Oli** [comment]
You can actually do that yourself, by changing the HISTORY_FILENAME setting in the config menu. You can put an absolute path in there, for example `/home/<user>/.local/share/rainbowstream/completer.hist`. Just make sure that directory exists first. 

This probably should be the default setting.

**Comment by b3yond** [comment]
Nice, thank you! this worked.

I would propose a file change in https://github.com/orakaro/rainbowstream/blob/master/rainbowstream/colorset/config, which is the default config copied over to .rainbow_config.json. but the problem with this path is, that the user's home directory can not be automatically added to the default config... maybe that key-value pair needs to be added to the .json in setup.py instead?

**Comment by b3yond** [comment]
Okay, I tried to treat .rainbow_config.json as a json file, to add the HISTORY_FILENAME key during setup.py.

this didn't work:  
```
>>> with open(default, "r+") as f:
...     config = json.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 2 column 5 (char 6)
```

**Comment by b3yond** [comment]
It seems to be possible, if you use 
```python
config.set_config("HISTORY_FILENAME", "/home/" + user + "/.local/share/rainbowstream")
```
already in setup.py... but it could be hard to import config.py during setup.py.

Is there a function which is only called once, at the first run of rainbowstream?

**Comment by b3yond** [comment]
I chose the method with the first-run-function instead: https://github.com/orakaro/rainbowstream/pull/245
