### ISSUE TITLE
Can't install/ run. 

### ISSUE THREAD

**Issue by beks0nn** [DTVD/rainbowstream#86]
OS: windows 8
Python: 2.7.9  

Isntall log..

C:\Python27>pip install rainbowstream
Collecting rainbowstream
  Using cached rainbowstream-1.2.5.tar.gz
    'cp' is not recognized as an internal or external command,
    operable program or batch file.
    'chmod' is not recognized as an internal or external command,
    operable program or batch file.
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in c:\
python27\lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): arrow in c:\python27\l
ib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python2
7\lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): pyfiglet in c:\python2
7\lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): twitter in c:\python27
\lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): Pillow in c:\python27\
lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): PySocks in c:\python27
\lib\site-packages (from rainbowstream)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in c:\python2
7\lib\site-packages (from python-dateutil->rainbowstream)
Installing collected packages: rainbowstream
  Running setup.py install for rainbowstream
    'cp' is not recognized as an internal or external command,
    operable program or batch file.
    'chmod' is not recognized as an internal or external command,
    operable program or batch file.
    Installing rainbowstream-script.py script to c:\Python27\Scripts
    Installing rainbowstream.exe script to c:\Python27\Scripts
    Installing rainbowstream.exe.manifest script to c:\Python27\Scripts
Successfully installed rainbowstream-1.2.5

C:\Python27>rainbowstream
The system cannot find the path specified.
Traceback (most recent call last):
  File "c:\Python27\Scripts\rainbowstream-script.py", line 9, in <module>
    load_entry_point('rainbowstream==1.2.5', 'console_scripts', 'rainbowstream')
()
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entr
y_point
    return ep.load()
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 2184, in load
    ['__name__'])
  File "c:\Python27\lib\site-packages\rainbowstream\rainbow.py", line 22, in <mo
dule>
    from .draw import *
  File "c:\Python27\lib\site-packages\rainbowstream\draw.py", line 15, in <modul
e>
    from .c_image import *
  File "c:\Python27\lib\site-packages\rainbowstream\c_image.py", line 24, in <mo
dule>
    rgb2short = call_c()
  File "c:\Python27\lib\site-packages\rainbowstream\c_image.py", line 19, in cal
l_c
    assert os.system(build + " >/dev/null 2>&1") == 0
AssertionError

C:\Python27>

**Comment by limeless** [comment]
you can try modify file c_image.py 
like I did, #83

**Comment by DTVD** [comment]
Hi @beks0nn , RS was not supported to be run in Window. 
Can you try the workaround like @limeless mentioned and tell me if it work ?
I'm sorry for your inconvenience

**Comment by beks0nn** [comment]
Thanks, with the change i get a new error.

C:\Python27>rainbowstream
Traceback (most recent call last):
  File "c:\Python27\Scripts\rainbowstream-script.py", line 9, in <module>
    load_entry_point('rainbowstream==1.2.5', 'console_scripts', 'rainbowstream')
()
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entr
y_point
    return ep.load()
  File "c:\Python27\lib\site-packages\pkg_resources.py", line 2184, in load
    ['__name__'])
  File "c:\Python27\lib\site-packages\rainbowstream\rainbow.py", line 22, in <mo
dule>
    from .draw import *
  File "c:\Python27\lib\site-packages\rainbowstream\draw.py", line 15, in <modul
e>
    from .c_image import *
  File "c:\Python27\lib\site-packages\rainbowstream\c_image.py", line 23, in <mo
dule>
    rgb2short = call_c()
  File "c:\Python27\lib\site-packages\rainbowstream\c_image.py", line 19, in cal
l_c
    image_c = ctypes.cdll.LoadLibrary(library)
  File "c:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by DTVD** [comment]
Sorry - maybe RS can't run on WindowOS due to one of its dependency compatibility with Window :disappointed: I think it will worth a try inside cygwin
