### ISSUE TITLE
Problems resuming after network disconnected and then reconnected

### ISSUE THREAD

**Issue by kramimus** [DTVD/rainbowstream#87]
Got this exception when coming back to my terminal running rainbowstream after resuming my laptop:

[@kramimus]: -- Heartbeat Timeout --
You can use switch command to return to your stream.
Type h stream for more details.
[@kramimus]: switch mine
 _                        _                     
| |                      (_)                    
| | ___ __ __ _ _ __ ___  _ _ __ ___  _   _ ___ 
| |/ / '__/ _` | '_ ` _ \| | '_ ` _ \| | | / __|
|   <| | | (_| | | | | | | | | | | | | |_| \__ \
|_|\_\_|  \__,_|_| |_| |_|_|_| |_| |_|\__,_|___/
                                                
                                                

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rainbowstream/rainbow.py", line 2068, in stream
    except (URLError, ConnectionResetError):
NameError: global name 'ConnectionResetError' is not defined

I assume it is because the network is off for a while and then comes back.

Also, I generally have problems making my stream resume after resuming my laptop.  Often the stream never resumes and I have to exit rainbowstream and start it again, even if I enter "switch mine".  It would be nice if it could just retry connecting after a few minutes so I would not have to do anything.

Version 1.2.5

**Comment by DTVD** [comment]
I see. I will look into this further and add a patch when have enough time . Thanks :+1:

**Comment by nevillepark** [comment]
Also got this bug, after fiddling with the time format and Unicode symbols in rainbow_config.json. Replaced it with the default config file and it went back to normal. 

```
 Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rainbowstream/rainbow.py", line 2080, in stream
    except (URLError, ConnectionResetError):
NameError: global name 'ConnectionResetError' is not defined
```
