### ISSUE TITLE
opening multiple lists...

### ISSUE THREAD

**Issue by murrayf** [DTVD/rainbowstream#89]
Hello,

First, congrats for rs is a great twitter client...

My question is about to open more than three user lists in various rs instances, Twitter API says "rate exceeded per user"... Is there any workaround for dealing with this? I have 5 lists in my user, my intention is open all of them at the same time...

Thanks a lot!

Alberto.

:)

**Comment by DTVD** [comment]
Hi @murrayf . That "rate exceeded" is Twitter's policy for clients and there is nothing I can do. But if you wait 15 minutes, don't use any other client and try again, everything will be back :smile:  
Ref: https://dev.twitter.com/rest/public/rate-limiting

**Comment by murrayf** [comment]
Hi again @DTVD ,

Today Tuesday, I tried successfully opening 5 list at the same time in several rs instances. It seems the twitter rate exceed API message happened on past Friday and Saturday, when probably there is more twitter traffic...

Thanks,

Alberto.

:)

**Comment by murrayf** [comment]
Hi @DTVD ,

    In previous posts I'd commented you that was impossible for me to open 5 twitter lists with my user at the same time with rainbowstream due to twitter API restrictions. I had got an twitter api message indicating me that this operation was not possible when I try to open the fourth list.

    Now I got a python error. I'd like you to review this code bellow (due I'm not able to decode it) to see if we have luck and they allow us to open more than 3 lists.

***************************
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/rainbowstream/rainbow.py", line 2003, in stream
    tweet_iter = stream.user(**query_args)
  File "/usr/lib/python2.7/site-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/lib/python2.7/site-packages/twitter/stream.py", line 284, in _handle_response
    _timeout or timeout, heartbeat_timeout)
  File "/usr/lib/python2.7/site-packages/twitter/stream.py", line 209, in handle_stream_response
    raise TwitterHTTPError(e, uri, 'json', arg_data)
  File "/usr/lib/python2.7/site-packages/twitter/api.py", line 72, in __init__
    data = json.loads(data.decode('utf8'))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

*************************************************************

 I'm using rainbowstream latest version from python pip in a Fedora 22 beta linux machine...

Thanks a lot,

Alberto.

:)
