### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by jdiedrick** [DTVD/rainbowstream#98]
Recently I've been getting this error. Any ideas?

(venv)Johanns-MacBook-Air:bin johanndiedrick$ rainbowstream
Traceback (most recent call last):
  File "venv/bin/rainbowstream", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2876, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 451, in _build_master
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 464, in _build_from_requirements
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 639, in resolve
pkg_resources.DistributionNotFound: rainbowstream==1.2.5
(venv)Johanns-MacBook-Air:python johanndiedrick$ 

OS: OS X Yosemite 10.10.2
Python version: 2.7.8

**Comment by DTVD** [comment]
Did you tried to unsintall and reinstall rainbowstream ?

**Comment by jdiedrick** [comment]
I ended up wiping my venv folder, creating a new one and reinstalling. Everything worked, and my credentials were intact as well. Not sure how to reproduce this, sorry! Feel free to close this if you want :)

**Comment by DTVD** [comment]
Glad that it worked for you :beer:
